### ISSUE TITLE
Code API

### ISSUE THREAD

**Issue by mikepurvis** [clearpathrobotics/enu#3]
The actual message-conversion and swift-nav wrappers should be broken out into separate functions, exposed in a header file, and properly documented. The from_fix and to_fix nodes should become clients of that API.

There are a variety of possible scenarios in which other C++ nodes might want to make these conversions internally without needing to pass the data through an RPC.

**Comment by chadrockey** [comment]
Agreed.  The first use I could think of is an rviz plugin.
